# Generated by Django 5.1.3 on 2024-11-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
